name: PrivateEnderWorlds
version: ${project.version}
main: codes.ephan.privateend.PrivateEndPlugin
api-version: 1.16
authors: [ ephan ]
description: Private Ender World plugin

commands:
  endworld:
    description: Opens the ender world menu
    usage: /endworld
